---
 - name: Distribute Kube API service config to controllers
   template: 
     src: /opt/pki-infrastructure/kube-apiserver.service.j2
     dest: /etc/systemd/system/kube-apiserver.service

 - name: Copy Kube controller manager kubeconfig to API directory
   copy:
     src: /root/kube-controller-manager.kubeconfig
     dest: /var/lib/kubernetes/kube-controller-manager.kubeconfig
     mode: 0600
     remote_src: yes

 - name: Distribute kube-api default abac policy
   copy:
     src: authorization-policy.jsonl
     dest: /var/lib/kubernetes/authorization-policy.jsonl
   
 - name: Distribute Kube controller manager service config to controllers
   copy:
     src: kube-controller-manager.service
     dest: /etc/systemd/system/kube-controller-manager.service

 - name: Copy Kube scheduler kubeconfig to API directory
   copy:
     src: /root/kube-scheduler.kubeconfig
     dest: /var/lib/kubernetes/kube-scheduler.kubeconfig
     mode: 0600
     remote_src: yes

 - name: Copy Kube scheduler manifest to Kubernetes directory
   copy:
     src: kube-scheduler.yaml
     dest: /etc/kubernetes/config/kube-scheduler.yaml
     mode: 0600

 - name: Distribute Kube scheduler service config to controllers
   copy:
     src: kube-scheduler.service
     dest: /etc/systemd/system/kube-scheduler.service

 - name: Reload systemd configuration
   systemd:
     daemon_reload: yes

 - name: Enable and start kube-api, kube-controller-manager, kube-scheduler services
   systemd:
     name: "{{ item }}"
     state: started
     enabled: yes
   with_items:
     - kube-apiserver
     - kube-controller-manager
     - kube-scheduler

