---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-gitlab-config
  labels:
    gitlab: config
spec:
  capacity: 
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: /mnt/nfs/gitlab/config
    server: 10.240.0.150
