---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    gitlab: storage
spec:
  capacity: 
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: /mnt/nfs/gitlab/storage
    server: 10.240.0.150
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    gitlab: registry
spec:
  capacity: 
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: /mnt/nfs/gitlab/registry
    server: 10.240.0.150
