---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "crawler-ui.fullname" . }}
  namespace: default
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ template "crawler-ui.fullname" . }}
          servicePort: {{ .Values.service.internalPort }}
