---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-elastic-disk
  labels:
    app: elasticsearch
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: /mnt/nfs/elasticsearch
    server: 10.240.0.150
