apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
{{- if .Values.metrics.enabled }}
  - name: metrics
    port: 9216
    targetPort: metrics
  selector:
    app: {{ template "mongodb.fullname" . }}
{{- end }}
