---
- name: TASK 1 ----------- Install python
  hosts: tag_{{ cluster_name }}-worker:tag_{{ cluster_name }}-controller
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
    
  roles:
    - 01_install_python
