---
- name: TASK 2 ----------- Local install client tools
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  vars_files:
    - vars.yml
    
  roles:
    - 02_install_prerequisites
