---
- name: TASK 13 ----------- Distribute kubernetes configs to controllers
  hosts: tag_{{ cluster_name }}-controller
  become: yes
  vars_files:
    - vars.yml

  roles:
    - 13_download_and_install_kubernetes_controller_binaries

