---
 - name: Install socat, conntrack and ipset via apt
   apt:
     name: "{{ item }}"
     state: present
   with_items:
     - socat
     - conntrack
     - ipset
     - nfs-common

 - name: Download kube binaries
   get_url:
     url: https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/{{ item }}
     dest: /usr/local/bin/{{ item }}
     mode: 0755
   with_items:
     - kubectl
     - kube-proxy
     - kubelet

 - name: Download CRI tools
   get_url:
     url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.12.0/crictl-v1.12.0-linux-amd64.tar.gz
     dest: /tmp/crictl-v1.12.0-linux-amd64.tar.gz

 - name: Download runsc tool
   get_url:
     url: https://storage.googleapis.com/kubernetes-the-hard-way/runsc-50c283b9f56bb7200938d9e207355f05f79f0d17
     dest: /usr/local/bin/runsc
     mode: 0755

 - name: Download runc tool
   get_url:
     url: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64
     dest: /usr/local/bin/runc
     mode: 0755

 - name: Download CNI plugin
   get_url:
     url: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
     dest: /tmp/cni-plugins-amd64-v0.6.0.tgz

 - name: Download containerd
   get_url:
     url: https://github.com/containerd/containerd/releases/download/v1.2.0-rc.0/containerd-1.2.0-rc.0.linux-amd64.tar.gz
     dest: /tmp/containerd-1.2.0-rc.0.linux-amd64.tar.gz

 - name: Create installation directories
   file:
     path: "{{ item }}"
     state: directory
     recurse: yes
     mode: 0700
   with_items:
     - /etc/containerd/
     - /etc/cni/net.d
     - /opt/cni/bin
     - /var/lib/kubelet
     - /var/lib/kube-proxy
     - /var/lib/kubernetes
     - /var/run/kubernetes

 - name: Extract CRI binaries
   unarchive:
     src: /tmp/crictl-v1.12.0-linux-amd64.tar.gz
     dest: /usr/local/bin
     remote_src: yes

 - name: Extract cni-plugin binaries
   unarchive:
     src: /tmp/cni-plugins-amd64-v0.6.0.tgz
     dest: /opt/cni/bin/
     remote_src: yes

 - name: Extract containerd binaries
   unarchive:
     src: /tmp/containerd-1.2.0-rc.0.linux-amd64.tar.gz
     dest: /
     remote_src: yes

