apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/external-traffic: "OnlyLocal"
spec:
  type: NodePort
{{- if .Values.baseIP }}
  loadBalancerIP: {{ .Values.baseIP }}
{{- end }}
  ports:
  - port: 80
    name: http
    nodePort: 80
    targetPort: 80
  selector:
    app: nginx
apiVersion: v1
