kibana:
  image:
    repository: "kibana"
    tag: "5.4.3"
  ingress:
    enabled: true
    hosts:
      - kibana.z-project.tk
  env:
    SERVER_PORT: 5601
    ELASTICSEARCH_URL: http://elasticsearch-logging:9200

